### ISSUE TITLE
kustomizer - value for args is ignored unless command is also present

### ISSUE THREAD

**Issue by GeoffWilliams** [solarwinds/rkubelog#10]
**Overview**

I need to pass `--ignore-namespaces none` to `rkubelog` so that I can stream logs from the `kube-system` namespace. The default value for this parameter is `kube-system`.

I am seeing that the value for  `/spec/template/spec/containers/0/args` is always ignored unless I also specify `/spec/template/spec/containers/0/command`. This behaviour contradicts the [Kubernetes manual](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/) and _also_ the behaviour of a simple nginx deployment to the same cluster[1]

**Workaround**

For `args` to take effect, I had to update `rkubelog/logging-config-patch.yaml`

1. Add `command`
2. Remove default argument `rkubelog`

```yaml
- op: add
  path: /spec/template/spec/containers/0/args
  value: ["--ignore-ns", "none"] # dont ignore kube-system

- op: add
  path: /spec/template/spec/containers/0/command
  value: ["/app/rkubelog"] # args are ignored without this - why?

# rest of file unchanged
```

**More Info**

In both cases flags are passed to the pod, there seems to be something about the deployment itself that stops the command ever receiving the arguments even though kubernetes has set them, so its not a problem with the go code:

```
$ kubectl describe deployment rkubelog -n kube-system
Name:                   rkubelog
Namespace:              kube-system
CreationTimestamp:      Sun, 15 Nov 2020 00:53:16 +1100
Labels:                 app=rkubelog
Annotations:            deployment.kubernetes.io/revision: 15
Selector:               app=rkubelog
Replicas:               1 desired | 1 updated | 2 total | 0 available | 2 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app=rkubelog
                    kail.ignore=true
  Service Account:  rkubelog-sa
  Containers:
   rkubelog:
    Image:      quay.io/solarwinds/rkubelog:r17
    Port:       <none>
    Host Port:  <none>
    Args:
      rkubelog
      --ignore-ns
      none
```
```
$ kubectl describe replicaset rkubelog-6f89d5969d -n kube-system
Name:           rkubelog-6f89d5969d
Namespace:      kube-system
Selector:       app=rkubelog,pod-template-hash=6f89d5969d
Labels:         app=rkubelog
                kail.ignore=true
                pod-template-hash=6f89d5969d
Annotations:    deployment.kubernetes.io/desired-replicas: 1
                deployment.kubernetes.io/max-replicas: 2
                deployment.kubernetes.io/revision: 15
                deployment.kubernetes.io/revision-history: 3
Controlled By:  Deployment/rkubelog
Replicas:       1 current / 1 desired
Pods Status:    1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=rkubelog
                    kail.ignore=true
                    pod-template-hash=6f89d5969d
  Service Account:  rkubelog-sa
  Containers:
   rkubelog:
    Image:      quay.io/solarwinds/rkubelog:r17
    Port:       <none>
    Host Port:  <none>
    Args:
      rkubelog
      --ignore-ns
      none
    Environment:
      PAPERTRAIL_PROTOCOL:  <set to the key 'PAPERTRAIL_PROTOCOL' in secret 'logging-secret'>  Optional: false
      PAPERTRAIL_HOST:      <set to the key 'PAPERTRAIL_HOST' in secret 'logging-secret'>      Optional: false
      PAPERTRAIL_PORT:      <set to the key 'PAPERTRAIL_PORT' in secret 'logging-secret'>      Optional: false
      LOGGLY_TOKEN:         <set to the key 'LOGGLY_TOKEN' in secret 'logging-secret'>         Optional: false
    Mounts:                 <none>
  Volumes:                  <none>
Events:
  Type    Reason            Age    From                   Message
  ----    ------            ----   ----                   -------
  Normal  SuccessfulCreate  4m21s  replicaset-controller  Created pod: rkubelog-6f89d5969d-9fgj
```

```
$ kubectl exec -ti  rkubelog-6f89d5969d-9fgjx -n kube-system -- /bin/sh
/app $ ps -eaf
PID   USER     TIME  COMMAND
    1 1001      0:01 ./rkubelog
```

With both `args` and `command` set, it works as expected:

```shell
/app $ ps -eaf
PID   USER     TIME  COMMAND
    1 1001      0:00 /app/rkubelog --ignore-ns none
```

I'm confused why this only happens with this deployment. I've tried directly editing the files kustomizer would patch and get the same result. Kubernetes cluster is AWS EKS 1.17 but since I had to remove `value: ["rkubelog"]` once I added `command` it looks like `args` is ignored for everyone.
 

**Environment**

```
$ kubectl version 
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-eks-7c9bda", GitCommit:"7c9bda52c425d0d56d7b93f1377a826b4132c05c", GitTreeState:"clean", BuildDate:"2020-08-28T23:07:29Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

[1] Deliberately broken deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        args:
          - "--uh-oh"
```

Results in...

```
  Warning  Failed     71s (x5 over 2m47s)  kubelet, fargate-ip-192-168-101-66.ec2.internal  Error: failed to create containerd task: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"--uh-oh\": executable file not found in $PATH": unknown
```

...As expected
